"""JOGO DE ADIVINHAR O NÚMERO
CRIE UM JOGO SIMPLES ONDE O USUARIO DEVE ADIVINHAR UM NÚMERO
1 DEFINA UM NÚMERO SECRETO
2 O JOGADOR TERÁ UM NÚMERO LIMITADO DE 5 TENTATIVAS PARA ADIVINHAR O NÚMERO
3  CADA TENTATIVA O PROGRAMA DEVE DIZER SE O PALPITE FOI MUITO ALTO OU MUITO BAIXO
4 SE O JOGADOR ACERTAR O N- EM QUALQUER TENTATIVA , EXIBA UMA MENSAGEM DE PARABENS E ENCERRE O JOGO.
5 SE O JOGADOR ESGOTAR TODAS AS TENTATIVAS SEM ACERTAR, REVELE O NÚMER SECRETO E EXIBA UMA MENSAGEM GAME OVER """